"""全局常量与默认配置（尽量保持无副作用导入）。"""

# 报警平均置信度阈值：达到 65% 才认为有效
ALARM_AVG_CONF_THRESHOLD = 0.65

# Worker 默认节流：目标约每 2 秒 1 帧
DEFAULT_TARGET_PERIOD_S = 2.0

# RapidOCR / ORT 默认线程数（CPU）
DEFAULT_ORT_INTRA_THREADS = 2
DEFAULT_ORT_INTER_THREADS = 2

# OCR 预处理默认值（偏省 CPU）
DEFAULT_OCR_SCALE = 1.0
AUTO_SCALE_IF_SMALL = True
AUTO_SCALE_MIN_WIDTH = 300
AUTO_SCALE_MIN_HEIGHT = 120
AUTO_SCALE_VALUE = 1.5
DEFAULT_USE_CLAHE = False
DEFAULT_USE_EQUALIZE_HIST = False

